### ISSUE TITLE
Logger: timestamps do not stick to the end of the line on changing zoom level

### ISSUE THREAD

**Issue by YuryShkoda** [sasjs/utils#21]
Default zoom:
![image](https://user-images.githubusercontent.com/25773492/106117212-d77ecc80-6163-11eb-972d-33ffd65f36f9.png)
Zoom out:
![image](https://user-images.githubusercontent.com/25773492/106117624-42c89e80-6164-11eb-8846-9e348de6dc69.png)
Zoom in:
![image](https://user-images.githubusercontent.com/25773492/106117411-09902e80-6164-11eb-9c53-50306b5b6c3b.png)

**Comment by allanbowe** [comment]
closing this, as very low impact (purely visual, only happens when changing zoom)
